import { Inter } from 'next/font/google';
import Box from '@mui/material/Box';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Visualizador vôlei',
  description: 'Generated by create next app'
};

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Box pt={4} px={16}>
          {children}
        </Box>
      </body>
    </html>
  );
}
